// alert
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
// auth
export const DECODED_MYSELF = "DECODED_MYSELF"
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";
// doctor
export const TOGGLE_DR_AVAILABLE = "TOGGLE_DR_AVAILABLE";
export const GET_RANKING = "GET_RANKING";
export const GET_DR_PROFILE = "GET_DR_PROFILE";
export const CLEAR_DR_PROFILE = "CLEAR_DR_PROFILE";
export const CREATE_DR_PROFILE = "CREATE_DR_PROFILE";
export const UPDATE_DR_PROFILE = "UPDATE_DR_PROFILE";
export const ADD_WORKEXP = "ADD_WORKEXP";
export const DELETE_WORKEXP = "DELETE_WORKEXP";
export const ADD_EDUCATION = "ADD_EDUCATION";
export const DELETE_EDUCATION = "DELETE_EDUCATION";
export const ADD_TRAINING = "ADD_TRAINING";
export const DELETE_TRAINING = "DELETE_TRAINING";
export const ADD_AWARD = "ADD_AWARD";
export const DELETE_AWARD = "DELETE_AWARD";
export const GET_OPD = "GET_OPD";
export const GET_COMMENTS = "GET_COMMENTS";
export const REMOVE_COMMENTS = "REMOVE_COMMENTS";
// hospital
export const GET_HOS_PROFILE = "GET_HOS_PROFILE";
export const CLEAR_HOS_PROFILE = "CLEAR_HOS_PROFILE";
export const CREATE_HOS_PROFILE = "CREATE_HOS_PROFILE";
export const UPDATE_HOS_PROFILE = "UPDATE_HOS_PROFILE";